### ISSUE TITLE
Cant open port on MacOS

### ISSUE THREAD

**Issue by Oskar888** [jpnurmi/flutter_libserialport#105]
I have problem cuz i cant open port on MacOS, when i run same code on Windows it works.

**Comment by chochstedler** [comment]
Having the same issue. Did you get it resolved?

**Comment by Oskar888** [comment]
I confirm that work

**Comment by Oskar888** [comment]
Add the following to Debug and Release Entitlements
<key>com.apple.security.device.serial</key> <true/> works!
