### ISSUE TITLE
can't get availablePorts

### ISSUE THREAD

**Issue by wrjcs** [jpnurmi/flutter_libserialport#13]
Hello,
I run you plugin on android no root,
I can't get the availablePorts.
This is the devices I have, and they have permission.
![image](https://user-images.githubusercontent.com/7202194/113591198-e4241300-9633-11eb-9779-7b9c6779f298.png)

And if I give the path directly to new SerialPort("/dev/ttyUSER0"),
it throw permission denied , error 13.

But if I use the plugin serial_port_flutter, I can get the list.
Could you help me?
Thanks.

**Comment by lucafabbri** [comment]
We put permission handling in todo. 
Activity is tracked in #76 
Closed

**Comment by zhuminjunivan** [comment]
sunmi？
