### ISSUE TITLE
Capture the Weight value of a Precision Scale

### ISSUE THREAD

**Issue by joaovictorgarcia10** [jpnurmi/flutter_libserialport#15]
Hello my friend! Nice package!

My name is Jhon and I'm a flutter developer.

I'm working in a desktop project that I need to check the connection and capture the weight of a precison scale connected to computer by Serial USB.

Can your package help me? 

I'm seeing that the package can check the connection and show information about  the Serial USB Dispositive. But the weight? Can I capture that?

**Comment by jpnurmi** [comment]
Hi, do you know if [libserialport](https://sigrok.org/wiki/Libserialport) supports such functionality?

**Comment by lucafabbri** [comment]
Hi Joao,

once you have the socket open you can get the weight accordingly to your device specs. Usually there is some protocol to implement in order to ask the scale to return the current weight.

I close the issue as no development is necessary

**Comment by datpt11** [comment]
@joaovictorgarcia10 any update?
