### ISSUE TITLE
Not able to install app using flutter_libserial on android

### ISSUE THREAD

**Issue by learncodingforweb** [jpnurmi/flutter_libserialport#17]
```
* What went wrong:
A problem occurred configuring project ':flutter_libserialport'.
> NDK at Android/Sdk/ndk/21.1.6352462 did not have a source.properties file
```
Even through updated android studio to use latest version of NDK

**Comment by jpnurmi** [comment]
Hi, do I understand correctly that a plain Flutter counter example or such works fine, but as soon as flutter_libserialport is added as a dependency, the build error occurs?

**Comment by learncodingforweb** [comment]
Problem get resolved by uninstall and after that again installing sdk in android resolves the problem.
Able to install app in android, But getting 

**SerialPortError: Permission denied, error = 13**

Running on Android Version 8.1.0
how to resolve this issue in android?

**Comment by jpnurmi** [comment]
I don't know what kind of device you have, but hopefully a rooted one: https://github.com/jpnurmi/libserialport.dart/issues/3

**Comment by lucafabbri** [comment]
We put permission handling in todo. 
Activity is tracked in #76 
Closed
