### ISSUE TITLE
Process on using the library

### ISSUE THREAD

**Issue by lolcatsnin** [jpnurmi/flutter_libserialport#18]
Please excuse if im asking a simple question
Is there a set process to installing this manually thats outside the usual add to pubspec and import steps ?

**Comment by jpnurmi** [comment]
I'm afraid I don't understand the question. I don't think it's possible to use the API of a Dart package without adding it to pubspec and importing it.

**Comment by jpnurmi** [comment]
The respective pure Dart package aka [`libserialport`](https://pub.dev/packages/libserialport) allows you to build/deploy/load the libserialport C-library as you wish if that's what you're asking.

**Comment by lolcatsnin** [comment]
Hey sorry for the late reply. il have a gander at it again. i had got everything working nicely through the example i modified but bringing it all to a new project is what had stumped me so il give it another look.

**Comment by jpnurmi** [comment]
Now that I read the question again, I think the answer would be that no additional steps are required besides the usual pubspec.yaml changes and importing the lib. Oh, and the API is documented in the [libserialport](https://pub.dev/documentation/libserialport/latest/libserialport/libserialport-library.html) package.
