### ISSUE TITLE
flutter_libserialport does not work on Archlinux anymore

### ISSUE THREAD

**Issue by Kozzi11** [jpnurmi/flutter_libserialport#20]
I have been usinig it for few weeks with no problem, but today it end up with these errors:

	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:98:9: error: invalid application of 'sizeof' to an incomplete type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:106:15: error: incomplete definition of type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:106:27: error: use of undeclared identifier 'RTSXOFF'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:107:15: error: incomplete definition of type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:107:27: error: use of undeclared identifier 'CTSXON'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:108:15: error: incomplete definition of type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:108:27: error: use of undeclared identifier 'DTRXOFF'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:109:15: error: incomplete definition of type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:109:27: error: use of undeclared identifier 'DSRXON'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:118:7: error: incomplete definition of type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:118:22: error: use of undeclared identifier 'RTSXOFF'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:118:32: error: use of undeclared identifier 'CTSXON'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:118:41: error: use of undeclared identifier 'DTRXOFF'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:118:51: error: use of undeclared identifier 'DSRXON'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:121:8: error: incomplete definition of type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:121:21: error: use of undeclared identifier 'RTSXOFF'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:123:8: error: incomplete definition of type 'struct termiox'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:123:21: error: use of undeclared identifier 'CTSXON'
	/home/kozak/Vyvoj/Eurosat/etrackermanagetool/linux/flutter/ephemeral/.plugin_symlinks/flutter_libserialport/third_party/libserialport/linux_termios.c:125:8: error: incomplete definition of type 'struct termiox'
	fatal error: too many errors emitted, stopping now [-ferror-limit=]
	Exception: Build process failed

**Comment by Kozzi11** [comment]
It is issue with linux kernel version >=5.12, because in 5.12 they have removed some old dead code
https://github.com/torvalds/linux/blob/v5.12/include/uapi/linux/termios.h
vs
https://github.com/torvalds/linux/blob/v5.11/include/uapi/linux/termios.h

**Comment by jpnurmi** [comment]
I guess we could temporarily rip off the related code from the local copy in `third_party/libserialport` but reporting the issue upstream would be better: https://sigrok.org/bugzilla/describecomponents.cgi?product=libserialport (requires registration).

**Comment by Kozzi11** [comment]
this would not helped. I have try it. It would compile but still not works. But if I comment
#define HAVE_STRUCT_TERMIOX
in
~/.pub/hosted/pub.dartlang.org/flutter_libserialport-0.2.1/linux/libserialport/config.h

it works ok
