### ISSUE TITLE
Unhandled Exception: SerialPortError: Interrupted system call, errno = 4

### ISSUE THREAD

**Issue by LiveRock** [jpnurmi/flutter_libserialport#21]
I got the above error.
Can someone shed some light what this error all about?
Thanks

**Comment by arzakmiftakhul** [comment]
same problem

**Comment by arzakmiftakhul** [comment]
I have found the solution :
1. Enable serial port permission. You can follow [https://websistent.com/fix-serial-port-permission-denied-errors-linux/](url). Don't forget to logout your desktop account first to take effect.
2. Make sure the port is open. You can check it using `port.isOpen();`
adding `port.open(mode: 1);`

That's work on my ubuntu + arduino (as data source)

**Comment by rishabh2791** [comment]
any update on this please...i am facing the same issue even though the port is open.
