### ISSUE TITLE
SerialPortError (SerialPortError: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by workoutand** [jpnurmi/flutter_libserialport#26]
![image](https://user-images.githubusercontent.com/88168152/127575090-eb89cf81-d8ea-47fe-ba60-76b20e7d6761.png)

Hi everyone,

I'm trying to run the example of the flutter_serialport lib, but it doesn't work on the android system, only windows, can anyone help me?

**Comment by jpnurmi** [comment]
Hi, perhaps the discussion at https://github.com/jpnurmi/libserialport.dart/issues/3 helps

**Comment by workoutand** [comment]
Hellow, I saw this thread but I didn't understand where those directories came from

**Comment by laychopy** [comment]
Someone made it work?

**Comment by josuemoraisgh** [comment]
Hello, I have the same problem and so far I haven't seen a solution on the forums. Can you help me?

**Comment by ampcontrolgroup** [comment]
Anyone with a solution for this?

**Comment by jeremylcarter** [comment]
Anyone with a solution for this?

**Comment by Fudal** [comment]
I have the same problem

**Comment by augustbering** [comment]
This lib should be updated to use the new android permissions handling, see https://github.com/altera2015/usbserial/blob/master/android/src/main/java/dev/bessems/usbserial/UsbSerialPlugin.java

That lib, usbserial, could be used instead of this one until it's fixed here I think.

**Comment by trapeye** [comment]
I have the same problem, is it fix yet?

**Comment by asrafilll** [comment]
still same problem guys, is it fix yet? Thanks

**Comment by eldhosekm** [comment]
am also having the same problem. any fix?

**Comment by augustbering** [comment]
only my "fix" from above

**Comment by eldhosekm** [comment]
I make it work using the native implementation of Flutter. in native use this in gradle io.github.xmaihh:serialport:2.1.1

**Comment by Muaz-fmb** [comment]
> I make it work using the native implementation of Flutter. in native use this in gradle io.github.xmaihh:serialport:2.1.1

is it possible for you to put the steps on how you solved it, unfortunately, I have zero knowledge of the native structure.

**Comment by eldhosekm** [comment]
you can use MethodChannel to communicate to native here is the sample. You will get the callback in flutter from java or kotlin. 

https://medium.com/@iiharish97ii/method-channel-in-flutter-bridging-native-code-and-flutter-with-two-way-communication-788d1e91c8c1

then you write the code in native (java or kotlin) using this library( io.github.xmaihh:serialport:2.1.1) to communicate with serial port.

**Comment by Muaz-fmb** [comment]
> you can use MethodChannel to communicate to native here is the sample. You will get the callback in flutter from java or kotlin.
> 
> https://medium.com/@iiharish97ii/method-channel-in-flutter-bridging-native-code-and-flutter-with-two-way-communication-788d1e91c8c1
> 
> then you write the code in native (java or kotlin) using this library( io.github.xmaihh:serialport:2.1.1) to communicate with serial port.

Can you help me with setting it up? it won't be for free. 
reach me out on mouazsysy@gmail.com

**Comment by guyluz11** [comment]
Having the same problem while running flutter on Linux

**Comment by lucafabbri** [comment]
We put permission handling in todo. 
Activity is tracked in #76 
Closed
