### ISSUE TITLE
BaudRate

### ISSUE THREAD

**Issue by BrenoNaSa** [jpnurmi/flutter_libserialport#31]
Hello everyone, 

I am from Brasil and my name is Breno Santos.  

Nowaday i'm using your library flutter_libserialport to work and i would like to know if is possible to change the BaudRate, how can i do that? It seens that value is fixed at 9600, i would like to use others value. 
Looking foward to hear from you soon.   

Best Regards!

**Comment by BrenoNaSa** [comment]
Thank you, I will try.

**Comment by lucafabbri** [comment]
@BrenoNaSa please have a look to #29 
config should be passed after opening the serial.
