### ISSUE TITLE
Flutter automatic installation error

### ISSUE THREAD

**Issue by luoqiang110** [jpnurmi/flutter_libserialport#41]
The following error occurs when I create a Windows desktop application and call Flutter_libserialport: ^0.2.3  :

[libserialport] flutter pub get
Running "flutter pub get" in libserialport...                   
Because libserialport depends on flutter_libserialport ^0.2.3 which depends on libserialport ^0.2.0, libserialport ^0.2.0 is required.
So, because libserialport is 1.0.0+1, version solving failed.
pub get failed (1; So, because libserialport is 1.0.0+1, version solving failed.)
exit code 1

**Comment by lucafabbri** [comment]
this is fixed in 0.4.0
