### ISSUE TITLE
Built white screen problem

### ISSUE THREAD

**Issue by ertugrulcakici** [jpnurmi/flutter_libserialport#48]
![image](https://user-images.githubusercontent.com/72172226/158039554-1eefe392-d59e-4e66-917a-a4e868729bdd.png)

When I built the app and run on windows, I got this white screen. If I delete the lines that I used libserial, it is behaving normally. In debug mode, there is no problem but when I built and use it anywhere, it just behaves like this.

![image](https://user-images.githubusercontent.com/72172226/158039597-97d0df22-6ad6-4d10-9d51-b111c28f3264.png)
![image](https://user-images.githubusercontent.com/72172226/158039606-ce37ad96-7766-41c4-95c4-543c102aad0f.png)

**Comment by lucafabbri** [comment]
This is related to #12
