### ISSUE TITLE
Can't build for android because of  HAVE_STRUCT_TERMIOX

### ISSUE THREAD

**Issue by augustbering** [jpnurmi/flutter_libserialport#50]
Seems this issue still remains for Android https://github.com/jpnurmi/flutter_libserialport/issues/20
not sure if it's still not released for flutter_libserialport, I'm using 0.2.3 so I think that fix should have been merged. Anyway, the way I fix this is to comment out

#define HAVE_STRUCT_TERMIOX 1

in my /.pub-cache/hosted/pub.dartlang.org/flutter_libserialport-0.2.3/android/libserialport/config.h

**Comment by tanweilong** [comment]
same here. Any solutions?

**Comment by augustbering** [comment]
Well, it seems the android port is quite broken either way, for new versions of android it needs to request permissions and there's no code for that in here. So some work required there.

**Comment by lucafabbri** [comment]
This is fixed in 0.4.0
