### ISSUE TITLE
how can I get 0x13 or 0x11 from port

### ISSUE THREAD

**Issue by LeiQiao** [jpnurmi/flutter_libserialport#6]
my code:

    commPort = SerialPort(portName);
    if (!commPort.openReadWrite()) {
      print(SerialPort.lastError);
      return false;
    }

    commPort.config.rts = SerialPortRts.on;
    commPort.config.cts = SerialPortCts.flowControl;
    commPort.config.xonXoff = SerialPortXonXoff.disabled;
    commPort.config.setFlowControl(SerialPortFlowControl.rtsCts);

disable xonxoff and set flow control to rts/cts, but still canot get 0x13 and 0x11, please help me.

**Comment by Windlesss** [comment]
> my code:
> 
> ```
> commPort = SerialPort(portName);
> if (!commPort.openReadWrite()) {
>   print(SerialPort.lastError);
>   return false;
> }
> 
> commPort.config.rts = SerialPortRts.on;
> commPort.config.cts = SerialPortCts.flowControl;
> commPort.config.xonXoff = SerialPortXonXoff.disabled;
> commPort.config.setFlowControl(SerialPortFlowControl.rtsCts);
> ```
> 
> disable xonxoff and set flow control to rts/cts, but still canot get 0x13 and 0x11, please help me.

seems it works now, thanks for your code
