### ISSUE TITLE
How can i decode data from RS232 port

### ISSUE THREAD

**Issue by fujimihikari** [jpnurmi/flutter_libserialport#63]
i get this value from RS232 port value

flutter: Read Data : [95, 24, 254]
flutter: Read Data : [95, 0, 254]
flutter: Read Data : [15, 32, 254]
flutter: Read Data : [15, 32, 254]
flutter: Read Data : [15, 0, 254]

how can i decode this value to readable String ?

**Comment by MihirGit1** [comment]
`reader.stream.map((data) => print(String.fromCharCodes(data)));`
