### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by pieterbergmans** [jpnurmi/flutter_libserialport#64]
Hi...I was wondering if this library will offer iOS support soon?  I noticed that https://pub.dev/packages/libserialport is currently supporting it.

Thanks.

**Comment by karniv00l** [comment]
I think that's a mistake, as far as I know you can't use serial port via USB or via bluetooth classic because of the MFi (made for iPhone) program. The only option is to use BLE for communication

**Comment by marcio-pessoa** [comment]
I believe @pieterbergmans got confused with iOS and macOS. Both are different things.

As @karniv00l wrote, libserialport does not support iOS.
https://pub.dev/packages/libserialport

Probably this issue could be closed.
