### ISSUE TITLE
flutter_libserialport stopped working suddenly

### ISSUE THREAD

**Issue by Ankur261** [jpnurmi/flutter_libserialport#67]
This library was just working fine for me than suddenly it stopped working on 26/12/22. I am using it to get data from a single phase meter. It's look like this library could not be able to write or read data from serial port. I used other software to read/write data and they the working perfectly. Anyone else facing this issue?

**Comment by toplinuxsir** [comment]
Yes, I face the same problem on windows 10 os , and flutter 3.13.4
