### ISSUE TITLE
How to select RS232/RS422/RS485 protocol 

### ISSUE THREAD

**Issue by hosseinvejdani** [jpnurmi/flutter_libserialport#73]
Hi. 
I'm creating a Flutter Linux app for running on a PC panel device. How to select RS232/RS422/RS485 protocol for a device that have one serial interface that support all protocols (RS232/RS422/RS485 ).

**Comment by lucafabbri** [comment]
I might be wrong but RSXXX standards defines the hardware port layout, but has nothing to do with serial communication.
I close this now, if you feel that I'm missing something reopen it ;)
