### ISSUE TITLE
How to set the baud rate ?

### ISSUE THREAD

**Issue by shessafridi** [jpnurmi/flutter_libserialport#93]
How do we set the baud rate for the port ?

**Comment by mihailacusteanu** [comment]
is this working for you?
```
SerialPort port = SerialPort("my port");
final config = SerialPortConfig();
config.baudRate = 115200;
port.config = config;
```

**Comment by shessafridi** [comment]
> is this working for you?
> 
> ```
> SerialPort port = SerialPort("my port");
> final config = SerialPortConfig();
> config.baudRate = 115200;
> port.config = config;
> ```

Yes, thank you

**Comment by mihailacusteanu** [comment]
@shessafridi did you manage to read data?
As I described in #94 I am not sure how to read serial port until end of line
